name = "ComplexElliptic"
uuid = "fc032641-0a8e-429a-9c5f-63deb23bae7a"
authors = ["Tina Torabi <tntorabii@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
