name = "ComplexElliptic"
uuid = "fc032641-0a8e-429a-9c5f-63deb23bae7a"
authors = ["Tina Torabi <tntorabii@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
